GET http://127.0.0.1:8080/acp/api/v1/ilp-endpoint

###

GET http://127.0.0.1:8080/acp/api/v1/config-value

###

GET http://127.0.0.1:8080/api/v1/acp/ilp-endpoint

<> 2026-01-23T190539.200.txt
<> 2026-01-23T150940.200.txt
<> 2026-01-23T150935.200.txt

###

POST 127.0.0.1:8080/acp/api/v1/ilp-endpoint
Content-Type: application/json

{
  "url": "http://example.com/ilp-endpoint",
  "auth_token": "your_auth_token_here"
}

### get the endpoint for S3 operations
GET http://127.0.0.1:8080/api/v1/acp/s3/endpoint

<> 2026-01-28T211122.200.txt

### list all S3 buckets
GET http://127.0.0.1:8080/api/v1/acp/s3/buckets

<> 2026-01-28T211611.200.json
<> 2026-01-28T211126.200.json

### list objects in a specific S3 bucket
GET http://127.0.0.1:8080/api/v1/acp/s3/list-objects/my-bucket

<> 2026-01-28T211723.200.json
<> 2026-01-28T211651.200.json
<> 2026-01-28T211633.200.json
<> 2026-01-28T211626.200.json

### create a new S3 bucket
PUT http://localhost:8080/api/v1/acp/s3/create-bucket/my-bucket

### create a new object in a specific S3 bucket
PUT http://localhost:8080/api/v1/acp/s3/create-object/my-bucket/my-object.txt
Content-Type: text/plain

This is the content of my-object.txt




###
GET http://localhost:8080/api/v1/acp/dynamo/endpoint

<> 2026-01-28T213410.200.txt

###
GET http://localhost:8080/api/v1/acp/dynamo/tables

<> 2026-01-28T213413.200.json


###
PUT http://localhost:8080/api/v1/acp/dynamo/create-table/abc
Content-Type: application/x-www-form-urlencoded

<> 2026-01-28T213416.500.json
###
GET http://localhost:8080/api/v1/acp/dynamo/list-objects/abc

<> 2026-01-28T213416.500.json
###
GET http://localhost:8080/api/v1/acp/dynamo/primary-key/abc


###
PUT http://localhost:8080/api/v1/acp/dynamo/create-object/abc/key-5678
Content-Type: text/plain

This is the content of my-object.txt


###
GET http://127.0.0.1:8080/api/v1/acp/s3/list-object-contents/acp







